Repository BAEDALPING/order-service, pull requests merged in 2024-08, with the labels that each got.

#5 공통 객체 정의(감사, 응답, 예외)
  build.gradle
  src/main/java/com/baedalping/delivery/DeliveryApplication.java
  src/main/java/com/baedalping/delivery/global/common/ApiResponse.java
  src/main/java/com/baedalping/delivery/global/common/AuditField.java
  src/main/java/com/baedalping/delivery/global/common/exception/DeliveryApplicationException.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/main/java/com/baedalping/delivery/global/common/exception/ExceptionControllerAdvice.java
  src/main/java/com/baedalping/delivery/global/config/JpaAuditConfig.java
  src/test/java/com/baedalping/delivery/DeliveryApplicationTests.java
Labels: ⚙️ Setting

#8 Feat/6 redis연동
  build.gradle
  src/main/java/com/baedalping/delivery/global/config/RedisConfig.java
  src/main/resources/application-local.yml
  src/test/java/com/baedalping/delivery/RedisConnectionTest.java
Labels: ⚙️ Setting, ✅ Test

#11 Feat/10 장바구니 기능 구현
  src/main/java/com/baedalping/delivery/cart/controller/CartController.java
  src/main/java/com/baedalping/delivery/cart/dto/CartRequestDto.java
  src/main/java/com/baedalping/delivery/cart/dto/CartResponseDto.java
  src/main/java/com/baedalping/delivery/cart/service/CartService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/test/java/com/baedalping/delivery/CartServiceTest.java
Labels: ✨ Feature, ✅ Test

#12 회원가입 API 추가 (#1)
  build.gradle
  src/main/java/com/baedalping/delivery/domain/user/controller/UserController.java
  src/main/java/com/baedalping/delivery/domain/user/dto/UserCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/UserCreateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/entity/User.java
  src/main/java/com/baedalping/delivery/domain/user/entity/UserAddress.java
  src/main/java/com/baedalping/delivery/domain/user/entity/UserRole.java
  src/main/java/com/baedalping/delivery/domain/user/repository/UserAddressRepository.java
  src/main/java/com/baedalping/delivery/domain/user/repository/UserRepository.java
  src/main/java/com/baedalping/delivery/domain/user/service/UserService.java
  src/main/java/com/baedalping/delivery/global/common/ApiResponse.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/main/java/com/baedalping/delivery/global/common/exception/ExceptionControllerAdvice.java
  src/main/java/com/baedalping/delivery/global/config/PasswordEncoder.java
  src/test/java/com/baedalping/delivery/user/UserControllerTest.java
  src/test/java/com/baedalping/delivery/user/UserServiceTest.java
Labels: ✨ Feature, ✅ Test

#9 Feat/3 product create을 위한 가게와 상품의 엔티티, 레포지토리 생성
  src/main/java/com/baedalping/delivery/product/Product.java
  src/main/java/com/baedalping/delivery/product/ProductRepository.java
  src/main/java/com/baedalping/delivery/productCategory/ProductCategory.java
  src/main/java/com/baedalping/delivery/productCategory/ProductCategoryRepository.java
  src/main/java/com/baedalping/delivery/store/Store.java
  src/main/java/com/baedalping/delivery/store/StoreRepository.java
  src/main/java/com/baedalping/delivery/storeCategory/StoreCategory.java
  src/main/java/com/baedalping/delivery/storeCategory/StoreCategoryRepository.java
Labels: ✨ Feature

#7 Feat/2 주문서생성
  src/main/java/com/baedalping/delivery/domain/cart/controller/CartController.java
  src/main/java/com/baedalping/delivery/domain/cart/dto/CartRequestDto.java
  src/main/java/com/baedalping/delivery/domain/cart/dto/CartResponseDto.java
  src/main/java/com/baedalping/delivery/domain/cart/service/CartService.java
  src/main/java/com/baedalping/delivery/domain/order/controller/OrderController.java
  src/main/java/com/baedalping/delivery/domain/order/dto/OrderCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/order/dto/OrderCreateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/order/dto/OrderDetailResponseDto.java
  src/main/java/com/baedalping/delivery/domain/order/entity/Order.java
  src/main/java/com/baedalping/delivery/domain/order/entity/OrderDetail.java
  src/main/java/com/baedalping/delivery/domain/order/entity/OrderStatus.java
  src/main/java/com/baedalping/delivery/domain/order/repository/OrderDetailRepository.java
  src/main/java/com/baedalping/delivery/domain/order/repository/OrderRepository.java
  src/main/java/com/baedalping/delivery/domain/order/service/OrderDetailService.java
  src/main/java/com/baedalping/delivery/domain/order/service/OrderService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/test/java/com/baedalping/delivery/CartServiceTest.java
Labels: ✨ Feature

#15 유저정보 수정 API 구현 (#13)
  src/main/java/com/baedalping/delivery/domain/user/controller/UserController.java
  src/main/java/com/baedalping/delivery/domain/user/dto/UserUpdateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/UserUpdateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/entity/User.java
  src/main/java/com/baedalping/delivery/domain/user/repository/UserRepository.java
  src/main/java/com/baedalping/delivery/domain/user/service/UserService.java
  src/main/java/com/baedalping/delivery/global/common/AuthenticationConfig.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/main/java/com/baedalping/delivery/global/config/AuditorAwareImpl.java
  src/main/java/com/baedalping/delivery/global/config/JpaAuditConfig.java
  src/test/java/com/baedalping/delivery/user/UserServiceTest.java
Labels: ✨ Feature

#19 유저 조회 및 탈퇴 API 구현 (#13)
  src/main/java/com/baedalping/delivery/domain/user/controller/UserController.java
  src/main/java/com/baedalping/delivery/domain/user/dto/UserReadResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/entity/User.java
  src/main/java/com/baedalping/delivery/domain/user/service/UserService.java
  src/main/resources/application-local.yml
  src/test/java/com/baedalping/delivery/user/UserFixture.java
  src/test/java/com/baedalping/delivery/user/UserServiceTest.java
Labels: ✨ Feature

#24 유저주소 등록 수정 조회 API 구현(#14)
  src/main/java/com/baedalping/delivery/domain/user/controller/UserController.java
  src/main/java/com/baedalping/delivery/domain/user/dto/request/UserAddressCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/request/UserAddressUpdateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/request/UserCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/response/UserAddressResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/response/UserCreateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/response/UserReadResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/response/UserUpdateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/entity/UserAddress.java
  src/main/java/com/baedalping/delivery/domain/user/repository/UserAddressRepository.java
  src/main/java/com/baedalping/delivery/domain/user/service/UserService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/test/java/com/baedalping/delivery/user/UserControllerTest.java
  src/test/java/com/baedalping/delivery/user/UserServiceTest.java
Labels: ✨ Feature

#27 feat: 결제 구현 (#23)
  src/main/java/com/baedalping/delivery/domain/payment/controller/PaymentController.java
  src/main/java/com/baedalping/delivery/domain/payment/dto/PaymentCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/baedalping/delivery/domain/payment/entity/Payment.java
  src/main/java/com/baedalping/delivery/domain/payment/entity/PaymentState.java
  src/main/java/com/baedalping/delivery/domain/payment/repository/PaymentRepository.java
  src/main/java/com/baedalping/delivery/domain/payment/service/PaymentService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: ✨ Feature

#29 Feat/28 주문취소
  src/main/java/com/baedalping/delivery/domain/order/controller/OrderController.java
  src/main/java/com/baedalping/delivery/domain/order/dto/OrderCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/order/dto/OrderGetResponseDto.java
  src/main/java/com/baedalping/delivery/domain/order/entity/Order.java
  src/main/java/com/baedalping/delivery/domain/order/entity/OrderType.java
  src/main/java/com/baedalping/delivery/domain/order/service/OrderService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: ✨ Feature

#31 필터 및 로그인 인증처리 구현(#25)
  build.gradle
  src/main/java/com/baedalping/delivery/domain/auth/dto/AuthLoginRequestDto.java
  src/main/java/com/baedalping/delivery/domain/auth/dto/AuthLoginResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/UserDetailsImpl.java
  src/main/java/com/baedalping/delivery/domain/user/repository/UserRepository.java
  src/main/java/com/baedalping/delivery/global/common/AuthenticationConfig.java
  src/main/java/com/baedalping/delivery/global/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/main/java/com/baedalping/delivery/global/common/exception/ExceptionControllerAdvice.java
  src/main/java/com/baedalping/delivery/global/config/AuditorAwareImpl.java
  src/main/java/com/baedalping/delivery/global/config/JpaAuditConfig.java
  src/main/java/com/baedalping/delivery/global/config/PasswordEncoder.java
  src/main/java/com/baedalping/delivery/global/config/RedisConfig.java
  src/main/java/com/baedalping/delivery/global/security/JwtAuthenticationFilter.java
  src/main/java/com/baedalping/delivery/global/security/JwtAuthorizationFilter.java
  src/main/java/com/baedalping/delivery/global/security/SecurityConfig.java
  src/main/java/com/baedalping/delivery/global/utils/JwtTokenUtils.java
  src/main/java/com/baedalping/delivery/global/utils/UserDetailServiceImpl.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#33 feat: 주문서검색 (#22)
  src/main/java/com/baedalping/delivery/domain/order/controller/OrderController.java
  src/main/java/com/baedalping/delivery/domain/order/entity/Order.java
  src/main/java/com/baedalping/delivery/domain/order/entity/OrderDetail.java
  src/main/java/com/baedalping/delivery/domain/order/repository/OrderRepository.java
  src/main/java/com/baedalping/delivery/domain/order/service/OrderService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: ✨ Feature

#36 refactor: 장바구니 권한체크 (#34)
  src/main/java/com/baedalping/delivery/domain/cart/controller/CartController.java
  src/main/java/com/baedalping/delivery/domain/cart/dto/CartProductDto.java
  src/main/java/com/baedalping/delivery/domain/cart/dto/ProductDto.java
  src/main/java/com/baedalping/delivery/domain/cart/service/CartService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
  src/test/java/com/baedalping/delivery/CartServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#38 refactor: 주문권한관리 (#37)
  src/main/java/com/baedalping/delivery/domain/order/controller/OrderController.java
  src/main/java/com/baedalping/delivery/domain/order/entity/Order.java
  src/main/java/com/baedalping/delivery/domain/order/service/OrderService.java
  src/main/java/com/baedalping/delivery/domain/payment/entity/Payment.java
  src/main/java/com/baedalping/delivery/domain/payment/service/PaymentService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: 🔨 Refactor

#41 order-service를 discovery client로 등록하고 UserDetils 필드 수정
  build.gradle
  src/main/java/com/baedalping/delivery/domain/user/dto/UserDetailsImpl.java
  src/main/java/com/baedalping/delivery/global/utils/UserDetailServiceImpl.java
  src/main/resources/application-local.yml
Labels: ⚙️ Setting

#30 Feat/26 가게 분류, 가게, 상품 분류, 상품 조회 및 검색 기능 구현
  src/main/java/com/baedalping/delivery/domain/product/controller/ProductController.java
  src/main/java/com/baedalping/delivery/domain/product/dto/ProductRequestDto.java
  src/main/java/com/baedalping/delivery/domain/product/dto/ProductResponseDto.java
  src/main/java/com/baedalping/delivery/domain/product/dto/ProductUpdateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/product/dto/ProductUpdateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/product/entity/Product.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/controller/ProductCategoryController.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/dto/ProductCategoryCreateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/dto/ProductCategoryRequestDto.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/dto/ProductCategoryResponseDto.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/dto/ProductCategoryUpdateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/entity/ProductCategory.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/repository/ProductCategoryRepository.java
  src/main/java/com/baedalping/delivery/domain/product/productCategory/service/ProductCategoryService.java
  src/main/java/com/baedalping/delivery/domain/product/repository/ProductRepository.java
  src/main/java/com/baedalping/delivery/domain/product/service/ProductService.java
  src/main/java/com/baedalping/delivery/domain/store/controller/StoreController.java
  src/main/java/com/baedalping/delivery/domain/store/dto/StoreCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/store/dto/StoreRequestDto.java
  src/main/java/com/baedalping/delivery/domain/store/dto/StoreResponseDto.java
  src/main/java/com/baedalping/delivery/domain/store/dto/StoreUpdateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/store/entity/Store.java
  src/main/java/com/baedalping/delivery/domain/store/repository/StoreRepository.java
  src/main/java/com/baedalping/delivery/domain/store/service/StoreService.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/controller/StoreCategoryController.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/dto/StoreCategoryCreateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/dto/StoreCategoryRequestDto.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/dto/StoreCategoryResponseDto.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/dto/StoreCategoryUpdateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/entity/StoreCategory.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/repository/StoreCategoryRepository.java
  src/main/java/com/baedalping/delivery/domain/store/storeCategory/service/StoreCategoryService.java
Labels: ✨ Feature

#43 유저 역할을 변경하는 어드민용 API 구현 (#32)
  src/main/java/com/baedalping/delivery/domain/user/controller/AdminController.java
  src/main/java/com/baedalping/delivery/domain/user/dto/request/UserRoleUpdateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/user/dto/response/UserAuthorityResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/entity/UserRole.java
  src/main/java/com/baedalping/delivery/domain/user/service/AdminService.java
Labels: ✨ Feature

#46 심화기능 - 유저권한 캐싱하고 유저 권한변경 시 캐시된 값 업데이트 하기 (#32)
  src/main/java/com/baedalping/delivery/domain/auth/AuthController.java
  src/main/java/com/baedalping/delivery/domain/auth/dto/UserCreateRequestDto.java
  src/main/java/com/baedalping/delivery/domain/auth/dto/UserCreateResponseDto.java
  src/main/java/com/baedalping/delivery/domain/user/controller/UserController.java
  src/main/java/com/baedalping/delivery/domain/user/service/UserService.java
  src/main/java/com/baedalping/delivery/global/config/RedisConfig.java
  src/main/java/com/baedalping/delivery/global/security/JwtAuthenticationFilter.java
  src/main/java/com/baedalping/delivery/global/security/SecurityConfig.java
  src/main/java/com/baedalping/delivery/global/utils/RedisComponent.java
  src/test/java/com/baedalping/delivery/user/UserControllerTest.java
Labels: ✨ Feature

#53 fix: 로그인 인증 오류 해결
  src/main/java/com/baedalping/delivery/domain/user/controller/UserController.java
  src/main/java/com/baedalping/delivery/domain/user/dto/UserDetailsImpl.java
  src/main/java/com/baedalping/delivery/domain/user/dto/response/UserAuthorityResponseDto.java
  src/main/java/com/baedalping/delivery/global/security/JwtAuthorizationFilter.java
  src/main/java/com/baedalping/delivery/global/security/SecurityConfig.java
  src/main/java/com/baedalping/delivery/global/utils/UserDetailServiceImpl.java
Labels: 🐞 Bug
