Repository BAEDALPING/order-service, pull requests merged in 2024-09, with the labels that each got.

#54 Feat/49 리뷰생성
  src/main/java/com/baedalping/delivery/domain/cart/service/CartService.java
  src/main/java/com/baedalping/delivery/domain/review/controller/ReviewController.java
  src/main/java/com/baedalping/delivery/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/baedalping/delivery/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/baedalping/delivery/domain/review/service/ReviewService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: ✨ Feature, 🐞 Bug

#55 feat: 리뷰 조회 (#50)
  src/main/java/com/baedalping/delivery/domain/review/controller/OwnerReviewController.java
  src/main/java/com/baedalping/delivery/domain/review/controller/ReviewController.java
  src/main/java/com/baedalping/delivery/domain/review/repository/ReviewRepository.java
  src/main/java/com/baedalping/delivery/domain/review/service/ReviewService.java
Labels: ✨ Feature

#56 feat: 리뷰 신고 (#51)
  src/main/java/com/baedalping/delivery/domain/review/controller/ReviewController.java
  src/main/java/com/baedalping/delivery/domain/review/dto/ReportReviewRequestDto.java
  src/main/java/com/baedalping/delivery/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/baedalping/delivery/domain/review/service/ReviewService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: ✨ Feature

#57 discovery client 설정 시 maveBom import
  build.gradle
  src/main/resources/application-local.yml
Labels: ⚙️ Setting

#60 feet: 유저 판별 로직 추가 (#42)
  src/main/java/com/baedalping/delivery/domain/product/controller/ProductController.java
  src/main/java/com/baedalping/delivery/domain/product/service/ProductService.java
  src/main/java/com/baedalping/delivery/domain/store/controller/StoreController.java
  src/main/java/com/baedalping/delivery/domain/store/entity/Store.java
  src/main/java/com/baedalping/delivery/domain/store/service/StoreService.java
  src/main/java/com/baedalping/delivery/domain/user/service/UserService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: ✨ Feature

#61 refactor: 주문 리팩토링 (#59)
  src/main/java/com/baedalping/delivery/domain/order/controller/OrderController.java
  src/main/java/com/baedalping/delivery/domain/order/controller/OwnerOrderController.java
  src/main/java/com/baedalping/delivery/domain/order/service/OrderService.java
  src/main/java/com/baedalping/delivery/global/common/exception/ErrorCode.java
Labels: 🔨 Refactor

#62 유저 엔드포인트들에 @AuthenticationPrinciple 적용
  src/main/java/com/baedalping/delivery/domain/user/controller/UserController.java
Labels: 🔨 Refactor

#63 심화기능 - 스프링 클라우드 게이트웨이로 유저 인증 분리하기 (#35)
  src/main/java/com/baedalping/delivery/global/config/RedisConfig.java
  src/main/java/com/baedalping/delivery/global/security/SecurityConfig.java
  src/main/java/com/baedalping/delivery/global/security/UserAuthorizationFilter.java
Labels: 🔨 Refactor, ✅ Test

#66 fix: 관리자 권한변경 API에서 CacheEvict key변경
  src/main/java/com/baedalping/delivery/domain/user/service/AdminService.java
Labels: 🐞 Bug, ✅ Test

#68 feat: 가게 허가, fix : 가게,상품 본인 아닐시 예외 던지도록 오류 수정
  src/main/java/com/baedalping/delivery/domain/product/service/ProductService.java
  src/main/java/com/baedalping/delivery/domain/store/entity/Store.java
  src/main/java/com/baedalping/delivery/domain/store/service/StoreService.java
  src/main/java/com/baedalping/delivery/domain/user/controller/AdminController.java
  src/main/java/com/baedalping/delivery/domain/user/service/AdminService.java
Labels: ✨ Feature
